# Generated by Django 2.2.7 on 2021-01-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20201229_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
