# Generated by Django 2.2.7 on 2021-01-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_category_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_time',
        ),
    ]
